import base64
from io import BytesIO
from pathlib import Path
from PIL import Image
import openai

from daily_chronicle.genai_client import GEMINI_IMG_MODEL, client_gemini
from daily_chronicle.slide_generation import temp_image_files
from daily_chronicle.utils_logging import emoji
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_random_exponential

def crop_center(img: Image.Image) -> Image.Image:
    """Crops the image to a square based on the shortest side."""
    width, height = img.size
    min_side = min(width, height)
    left = (width - min_side) / 2
    top = (height - min_side) / 2
    right = (width + min_side) / 2
    bottom = (height + min_side) / 2
    return img.crop((left, top, right, bottom))

def generate_image_gemini(prompt):
    result = client_gemini.models.generate_images(
        model=GEMINI_IMG_MODEL,
        prompt=prompt,
        config={
            "number_of_images": 1,
            "output_mime_type": "image/jpeg",
            "aspect_ratio": "1:1",
            "person_generation": "allow_adult"
        }
    )
    if not result.generated_images:
        raise ValueError("No images generated by Gemini.")
    return result.generated_images[0].image.image_bytes

def generate_image_openai(prompt):
    response = openai.images.generate(
        model="gpt-image-1",
        prompt=prompt,
        n=1,
        size="1024x1024",
        quality="auto",
    )
    image_b64 = response.data[0].b64_json
    image_bytes = base64.b64decode(image_b64)
    return image_bytes

@retry(wait=wait_random_exponential(multiplier=0.8, min=2, max=20),
        stop=stop_after_attempt(5))
def generate_image_gemini_with_backoff(prompt):
    return generate_image_gemini(prompt)

@retry(wait=wait_random_exponential(multiplier=0.8, min=2, max=20),
        stop=stop_after_attempt(5),
        retry=retry_if_exception_type((openai.RateLimitError, openai.Timeout))
        )
def generate_image_openai_with_backoff(prompt):
    return generate_image_openai(prompt)

def generate_event_image(event, index, generate_image_function, logger=print):
    prompt = event["image_prompt"]
    logger(f"🖼️ Generating image: \"{prompt}\"")

    # Generate image using the specified function
    try:
        image_bytes = generate_image_function(prompt)
        image = Image.open(BytesIO(image_bytes))

        image_out_path = Path("daily_chronicle") / "temp" / "temp_image_files" / f"event_image_{index + 1}.jpg"
        image_out_path.parent.mkdir(parents=True, exist_ok=True)
        image.save(image_out_path, format="JPEG")
        temp_image_files.append(str(image_out_path))

        logger(f"✅ Image saved: {str(image_out_path)}")
        return str(image_out_path)

    except Exception as e:
        logger(f"{emoji('cross_mark')} Image generation failed: {e}")

        # Use the existing placeholder image
        placeholder_path = Path("resources") / "image_fail_placeholder.jpg"
        return placeholder_path